#!/bin/bash

EUSLISP_PKGDIR=`rospack find euslisp`
EUS2_EXE=`find $EUSLISP_PKGDIR -name eus2`

if [ "$EUS2_EXE" ] ; then
    rosrun euslisp eus2 `rospack find roseus`/scripts/genmsg-main-eus.l -c "(prog1 (gensrv-eus \"$@\")(exit))" >> /dev/null
else
    exit 1
fi




