#!/bin/bash

EUSLISP_PKGDIR=`rospack find euslisp`
EUS2_EXE=`find $EUSLISP_PKGDIR -name eus2`

if [ "$EUS2_EXE" ] ; then
    $EUS2_EXE `rospack find geneus`/scripts/genmsg-main-eus.l -c "(prog1 (genmanifest-eus \"$1\")(exit))" >> /dev/null
fi






