#!/bin/bash

EUSLISP_PKGDIR=`rospack find euslisp`
EUS1_EXE=`find $EUSLISP_PKGDIR -name eus1 -executable`

if [ "$EUS1_EXE" ] ; then
    ARG=""
    for i in $@; do
        ARG="$ARG \"$i\""
    done
    $EUS1_EXE `rospack find geneus`/scripts/genmsg-main-eus.l -c "(prog1 (genmanifest-eus $ARG)(exit))" >> /dev/null
fi
