#!/bin/bash

EUSLISP_PKGDIR=`rospack find euslisp`
EUS2_EXE=`find $EUSLISP_PKGDIR -name eus2 -executable`

if [ "$EUS2_EXE" ] ; then
    $EUS2_EXE `rospack find geneus`/scripts/genmsg-main-eus.l -c "(prog1 (gensrv-eus \"$@\")(exit))" >> /dev/null
fi




