include $(shell rospack find mk)/cmake.mk

clean:
	-cd build && make clean
	rm -rf msg/cpp msg/lisp msg/oct msg/java msg/eus srv/cpp srv/lisp srv/oct srv/java srv/eus src/$(PACKAGE_NAME)/msg src/$(PACKAGE_NAME)/srv
	rm -rf build


