#!/bin/sh 

# file
FILE="\"$1\"";
shift
# argc
ARGV="(list"
while [ $# -ne 0 ]; do
    ARGV=$ARGV"\"$1\" ";
    shift;
done
ARGV=$ARGV")"

jskrbeusgl "(progn (if $ARGV (setq lisp::*eustop-argument* $ARGV))(load $FILE))" &
PID=$!
#echo PID is $PID
trap 'kill -s HUP $PID ' CHLD INT TERM
wait $PID
if [ $? -ne 0 ] ; then read line ; fi

